title: Lenovo HPC
email: hpchelp@lenovo.com
description: >
  Lenovo HPC resources, news, and documentation
baseurl: /VERSION
markdown: kramdown
plugins:
  - jekyll-toc

toc:
  min_level: 1
  max_level: 2

kramdown:
        input: GFM
        hard_wrap: false
        syntax_highlighter: none
        parse_block_html: true

